### PR TITLE
Add request headers into route context

### PR DESCRIPTION
**Pull request by cegerard**
This will allow developpers to get custom headers or cookies.
For instance it is usefull for authentication purpose.

### CODE REVIEW

**Comment by cegerard** [comment]
Hi, @austinkelleher, @philidem is there anyone that maintains this project ?

**Comment by austinkelleher** [comment]
@cegerard Sorry for late reply. Thanks for the reminder! 

I appreciate you taking the time to open this PR. I'm wondering if this old PR should be merged instead: https://github.com/marko-js/marko-starter-generic-server/pull/1

What do you think? Would you rather see the `rest.req.headers` object exposed or the entire `rest.req` exposed?

/cc @mlrawlings @DylanPiercey

**Comment by cegerard** [comment]
Thank for the reply @austinkelleher 
IMHO we don't need the full request object or if it is the case perhaps it will be more interesting to move to other solutions (express., etc.).

This modification is related to this PR https://github.com/marko-js/marko-starter/pull/41.

I personally prefer to keep thing as simple as possible.

**Comment by austinkelleher** [comment]
@cegerard Sounds fine to me. I'm going to go ahead and merge both of your PRs. Thanks again for your work!

**Review by austinkelleher — APPROVED** [review]

**Comment by austinkelleher** [comment]
Published `marko-starter-generic-server@v1.1.0`. Going to publish a new version of `marko-starter` too.

**Comment by cegerard** [comment]
Thank you.

**Pull request merged**
